name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: node18-linux-x64
            artifact_name: projectctl-linux
          - os: macos-latest
            target: node18-macos-x64
            artifact_name: projectctl-macos
          - os: windows-latest
            target: node18-win-x64
            artifact_name: projectctl-win.exe
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build standalone binary
        run: npx pkg dist/index.js --targets ${{ matrix.target }} -o ${{ matrix.artifact_name }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 